In [46]:
import numpy as np
import configparser
config = configparser.ConfigParser()
config.read("config.ini")

['config.ini']

In [31]:
idx_train_batch = [[] for _ in range(3)]
train_data_proportions = [200,300,500]


In [42]:
proportions_train = np.random.dirichlet(np.repeat(0.5,3))
proportions_train2 = proportions_train.copy()
print(proportions_train)
print(proportions_train2)

[0.09590152 0.82176992 0.08232856]
[0.09590152 0.82176992 0.08232856]


In [43]:
proportions_train = np.array([p*(len(idx_j)<train_data_proportions[i]) for i,(p,idx_j) in enumerate(zip(proportions_train,idx_train_batch))])

In [50]:
a = config["WORKER"]["batch_size"]
type(a)

str

In [40]:
for i, (p, idx_j) in enumerate(zip(proportions_train, idx_train_batch)):
    if len(idx_j) >= train_data_proportions[i]:
        proportions_train2[i] = 0  # 十分なデータが割り当てられている場合は0
    else:
        proportions_train2[i] = p  # そうでない場合はpのまま

In [44]:
print(proportions_train)
print(proportions_train2)

[0.09590152 0.82176992 0.08232856]
[0.09590152 0.82176992 0.08232856]
